// Mocks generated by Mockito 5.4.6 from annotations
// in offro_cibo/test/domain/repositories/user_food_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:offro_cibo/data/data_sources/firebase_firestore_food_service.dart'
    as _i4;
import 'package:offro_cibo/data/data_sources/firebase_firestore_user_service.dart'
    as _i6;
import 'package:offro_cibo/data/models/custom_user_dto.dart' as _i3;
import 'package:offro_cibo/data/models/food_dto.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFoodDTO_0 extends _i1.SmartFake implements _i2.FoodDTO {
  _FakeFoodDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCustomUserDTO_1 extends _i1.SmartFake implements _i3.CustomUserDTO {
  _FakeCustomUserDTO_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseFirestoreFoodServiceApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestoreFoodServiceApi extends _i1.Mock
    implements _i4.FirebaseFirestoreFoodServiceApi {
  MockFirebaseFirestoreFoodServiceApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.FoodDTO> addFood(_i2.FoodDTO? newFood) => (super.noSuchMethod(
        Invocation.method(
          #addFood,
          [newFood],
        ),
        returnValue: _i5.Future<_i2.FoodDTO>.value(_FakeFoodDTO_0(
          this,
          Invocation.method(
            #addFood,
            [newFood],
          ),
        )),
      ) as _i5.Future<_i2.FoodDTO>);

  @override
  _i5.Future<bool> deleteFood(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFood,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.FoodDTO> getFood(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFood,
          [id],
        ),
        returnValue: _i5.Future<_i2.FoodDTO>.value(_FakeFoodDTO_0(
          this,
          Invocation.method(
            #getFood,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.FoodDTO>);

  @override
  _i5.Future<_i2.FoodDTO> updateFood(_i2.FoodDTO? food) => (super.noSuchMethod(
        Invocation.method(
          #updateFood,
          [food],
        ),
        returnValue: _i5.Future<_i2.FoodDTO>.value(_FakeFoodDTO_0(
          this,
          Invocation.method(
            #updateFood,
            [food],
          ),
        )),
      ) as _i5.Future<_i2.FoodDTO>);

  @override
  _i5.Future<List<_i2.FoodDTO>> searchFood({
    required String? queryText,
    required List<String>? categoryIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFood,
          [],
          {
            #queryText: queryText,
            #categoryIds: categoryIds,
          },
        ),
        returnValue: _i5.Future<List<_i2.FoodDTO>>.value(<_i2.FoodDTO>[]),
      ) as _i5.Future<List<_i2.FoodDTO>>);

  @override
  _i5.Future<List<_i2.FoodDTO>> getFoodListByUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFoodListByUser,
          [userId],
        ),
        returnValue: _i5.Future<List<_i2.FoodDTO>>.value(<_i2.FoodDTO>[]),
      ) as _i5.Future<List<_i2.FoodDTO>>);
}

/// A class which mocks [FirebaseFirestoreUserServiceApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestoreUserServiceApi extends _i1.Mock
    implements _i6.FirebaseFirestoreUserServiceApi {
  MockFirebaseFirestoreUserServiceApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.CustomUserDTO> addUser(_i3.CustomUserDTO? newUser) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [newUser],
        ),
        returnValue: _i5.Future<_i3.CustomUserDTO>.value(_FakeCustomUserDTO_1(
          this,
          Invocation.method(
            #addUser,
            [newUser],
          ),
        )),
      ) as _i5.Future<_i3.CustomUserDTO>);

  @override
  _i5.Future<void> getUserByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserByEmail,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.CustomUserDTO> getUserById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValue: _i5.Future<_i3.CustomUserDTO>.value(_FakeCustomUserDTO_1(
          this,
          Invocation.method(
            #getUserById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.CustomUserDTO>);

  @override
  _i5.Future<_i3.CustomUserDTO> updateUser(_i3.CustomUserDTO? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i5.Future<_i3.CustomUserDTO>.value(_FakeCustomUserDTO_1(
          this,
          Invocation.method(
            #updateUser,
            [user],
          ),
        )),
      ) as _i5.Future<_i3.CustomUserDTO>);
}
